import { Inter } from 'next/font/google'
import './globals.css'
import "@/assets/style.scss";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio site by nextjs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel='icon'type='image/svg+xml'href='favicon.svg'/>
      <body>{children}</body>
    </html>
  )
}
